version: "3.1"

services:
  psql:
    image: psql
    secrets:
      - psql_user
      - psql_pass
    environment:
      POSTGRESS_USER_FILE: /run/secrets/psql_user
      POSTGRES_PASSWORD_FILE: /run/secrets/psql_pass

secrets:
  psql_user:
    file: ./psql_user.txt
  psql_pass:
    file: ./psql_pass.txt
