pipeline {
	agent any
	tools{
		maven "MAVEN3"
		jdk "JDK17"
	}
	stages{
		stage('Fetch the code') {
			steps {
				git branch: 'main', url: 'https://github.com/r0jjames/acn-backend-holiday-assignment.git'
			}
		}
		stage('Build') {
			steps{
				dir("holiday") {
				sh 'mvn install  -DskipTests'
				}
			}
			post{
				success {
					echo 'Archiving artifacts now.'
					archiveArtifacts artifacts: '**/target/*.jar'
				}
			}
		}
		stage('Unit Tests') {
			steps {
				// sh 'mvn test'
				echo 'Unit tests.....'
			}
		}
		
	}
	post {
        always {
            // Archive the build artifacts
            archiveArtifacts artifacts: 'target/*.jar', allowEmptyArchive: true
        }
        success {
            echo 'Build and run successful!'
        }
        failure {
            echo 'Build or run failed.'
        }
    }
}